plugins:
- grafana-kubernetes-app

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

grafana.ini:
  auth.github:
    enabled: true
    allow_sign_up: true
    # client_id:
    # client_secret:
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
